# Generated by Django 4.2 on 2023-04-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disks", "0002_rename_albums_track_album"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="artists",
            new_name="artist",
        ),
    ]
